version: "3.9"

services:
  app:
    build:
      dockerfile: ./docker/Dockerfile
    shm_size: 2gb
    volumes:
      - ./main.py:/main.py
      - ./screenshots:/screenshots:cached
      - ./files:/files:cached
      - ./src:/src:cached
    command: 'python3 main.py'
    